Refractored some parts and added a debug option
jexia/deploy-action pull request #1
Opened 2020-04-24 20:45 UTC by BaileyJM02

Updated a few logic statements to simplify the code and created a `debug` option to ensure that no secret values are knowingly output to the console.

2020-04-25 13:17 UTC, BaileyJM02 commented
This pull request has the following changes:
- We now rely on `grep` for pattern matching ([L80-81](https://github.com/jexia/deploy-action/pull/1/files#diff-60254338249f657a0a83f98258a56bfeR80-R81)) to prevent some errors we got before when the `$OUTPUT` was not formatted as expected
- A new error handling process to return more useful outputs when `$STATUS` is not set (i.e the `$OUTPUT` value was not what we expected. ([L83-112](https://github.com/jexia/deploy-action/pull/1/files#diff-60254338249f657a0a83f98258a56bfeR83-R112))
- A new `debug` option for users to include *possibly sensitive* data in the output, see the `README.md` file. This first image is with `debug: false` (default):
![image](https://user-images.githubusercontent.com/19824075/80280502-673aaa80-86fc-11ea-8e11-d9d6b4afaee2.png)
This second image is with `debug: true`:
![image](https://user-images.githubusercontent.com/19824075/80280519-7cafd480-86fc-11ea-9ca0-04d9786b9d41.png)
- A new **internal** `serious_error` function to ignore the `silent_fail` option. ([L11-14](https://github.com/jexia/deploy-action/pull/1/files#diff-60254338249f657a0a83f98258a56bfeR11-R14))
- Better text color handling for readability and maintainability.

---

This will be released in a semantic version `1.1.0` due to new features.

2020-04-26 06:34 UTC, veger requested changes
You might want to the rest of script for missing quotes around strings, I tried to mark them all, but unchanged lines I did not check.

2020-04-26 06:34 UTC, veger commented on deploy.sh
> +if [ "$INPUT_WAIT" = true ]; then
`true` is also a string, so best to quote it (although we know it is always there and does not contain spaces, it is best to always quote strings)

```suggestion
if [ "$INPUT_WAIT" = "true" ]; then
```

2020-04-26 06:34 UTC, veger commented on deploy.sh
> +    echo -e "\e[33mWarning: '--wait' flag added. Jexia can take around 7 minutes to deploy. This will wait for the whole duration.${RESET_COLOR}"
Missed replacing the color code to the more readable variables

2020-04-26 06:34 UTC, veger commented on deploy.sh
> +    if [ "$INPUT_DEBUG" = true ]; then
```suggestion
    if [ "$INPUT_DEBUG" = "true" ]; then
```

2020-04-26 06:34 UTC, veger commented on deploy.sh
> +    if [ "$INPUT_SILENT_FAIL" = true ] && [ "$SERIOUS_ERROR" = false ]; then
```suggestion
    if [ "${INPUT_SILENT_FAIL}" = "true" ] && [ "${SERIOUS_ERROR}" = "false" ]; then
```

(for consistency reasons I would use the `${variable}` format here as well, like you did in the rest of the script)

2020-04-26 10:21 UTC, BaileyJM02 commented
Hi @veger, thank you for the review, I have ammended the areas you have mentioned. Do you think this is now ready for the `v1.1.0` release?

2020-04-27 06:55 UTC, veger approved these changes

2020-04-27 06:56 UTC, veger commented
Looks good to me

2020-04-27 08:44 UTC, merged